# Generated by Django 2.2.11 on 2020-04-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20200411_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchs',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
